### ISSUE TITLE
Update Design of Logo

### ISSUE THREAD

**Issue by sstatz** [flexion/10x-website#29]

**Comment by npage123** [comment]
@nico @Will Cahoe Would love some feedback on the updated logo. Included are a version over a light background, version over dark background, and a more black and white version. 

![Screen Shot 2020-10-21 at 4.19.06 PM.png](https://images.zenhubusercontent.com/58f7701e51aa2c30577bd12c/041ac705-3b17-4b2c-b597-acb1b43cc917)

**Comment by npage123** [comment]
Per feedback from Nico: 

_"Can you flip the colors on the black background? So it’s a mint 10 with an orange ombre? I know we can do this forever — I just want to see how it looks. Thanks!"_

heres a version of the 'Ocean' and 'Tiger' colors swapped.

![Screen Shot 2020-10-22 at 9.36.05 AM.png](https://images.zenhubusercontent.com/58f7701e51aa2c30577bd12c/64f1f1d9-885a-4b8f-98ef-e5b6c6575409)

**Comment by npage123** [comment]
@willcahoe and Nico, here are two different sets of the logo where the gradient of the X has been adjusted slightly. Both sets include a version of the logo over light, dark, and black and white. Both sets are also using a 45 degree angle for the gradient (on previous versions it was a vertical gradient at 0 degrees). Set A shows more of the Orange and Lead colors and Set B shows more of the Ocean and Smoke colors. Feedback is welcome.

![Screen Shot 2020-10-27 at 4.08.32 PM.png](https://images.zenhubusercontent.com/58f7701e51aa2c30577bd12c/b364b022-ab22-4a4c-a34e-da8496397c03)

**Comment by npage123** [comment]
Final logo approved! Files below. 10x-logo-light.svg should be used over light background, 10x-logo-dark.svg should be used over dark backgrounds.

![10x-logo-dark.svg](https://images.zenhubusercontent.com/58f7701e51aa2c30577bd12c/7773fdcc-a9e9-4700-9bd4-46fc844dcaa1)
